import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  rust: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ],
};

export default sidebars;
