import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  ffmpeg: [
    {
      type: 'category',
      label: 'FFmpeg 命令行工具',
      // 'linux' 是你在 docusaurus.config.ts 中设置的 `path` (即内容目录名)
      // dirName: '.', 表示自动生成侧边栏，从 'linux' 目录下所有文件开始
      // 如果你想指定从 'linux/introduction' 开始，可以写 dirName: 'introduction'
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
  ],
};

export default sidebars;
