import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    spring: [
        {
            type: 'autogenerated',
            dirName: '.'
        }
    ],
};

export default sidebars;
